---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
          - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Ensure Docker is running
        run: |
          sudo systemctl start docker
          docker info

      - name: Install test dependencies
        run: pip3 install molecule docker yamllint ansible-lint

      - name: Run molecule tests.
        run: molecule test